### ISSUE TITLE
O.o is hard to debug

### ISSUE THREAD

**Issue by bcherny** [arv/ecmascript-object-observe#23]
Let's say this is your program:

```js
let obj = {
  a: 1
}
Object.observe(obj, () => console.log('changed!'))
function a() { obj.a = 2 }
function b() { obj.a = 2 }
```

And in your console you see

```text
> changed!
```

How do you know if the `log` was triggered by function `a()` or `b()`? In practice it's probably an antipattern to care about the source of a change event in your code, but when a value erroneously changed, it's often hard to debug exactly *why* it changed.

Some sort of call stack with each observer fire would be helpful. Alternatively, should we rely on devtools to provide instrumentation for this, like it already does for Promises and other async "call stacks"?

Also see https://github.com/angular/angular.js/issues/12606

**Comment by arv** [comment]
This seems like something a debugger should be responsible for... just like it provides an async stack for promises/xhr/timeouts/etc.
