### ISSUE TITLE
Array.observe : consider adding added element to splice change

### ISSUE THREAD

**Issue by mjeanroy** [arv/ecmascript-object-observe#24]
Hi,

We can observe splice changes to arrays and check for added elements such as:

``` javascript
Array.observe(array, function(changes) {
  changes.forEach(function(change) {
    var index = change.index;
    var added = change.object.slice(index, index + change.addedCount);
    console.log('added elements: ', added);
  });
});
```

This seems easy, but suppose you are adding elements to the array at different index. Here is a very simple test case:

``` javascript
var array = [0, 1, 2];
array.unshift(3);
array.unshift(4);
```

In this case, you will have two changes:
- First : `{ type: 'splice', index: 0, addedCount: 1, removed: [], object: array }`
- Second : `{ type: 'splice', index: 0, addedCount: 1, removed: [], object: array }`

So if you use the observer function given above, you will log the same object for both changes.

**Conclusion**: it is not trivial to retrieve added elements by using only change information. You have to check next changes (in other word: you have to "check the future" !) to be sure nothing has been added before or at the same index.

Before the second `unshift` operation, we could trigger previous changes to observers using `Object.deliverChangeRecords` function, but there are a lot of cases where you don't want to trigger a synchronous callback in the middle of something. 

So, it would be really great to get added elements from the change object, this way it would be really easy to iterate over changes and apply diff to a dom tree for example.

Maybe I am totally wrong, what do you think ?

**Comment by arv** [comment]
We don't provide the new value in `"update"` either so at least it is consistent.

The goal has always been to be able to get a consistent view at each microtask and that is doable without adding `newValue` or added elements. You can process the stream of records at each microtask to add this information without any changes to this spec proposal.

**Comment by mjeanroy** [comment]
> You can process the stream of records at each microtask to add this information without any changes to this spec proposal.

I am not saying this is impossible, but it can be really hard.
My previous test case is very simple, and it's not so complicated to implement a fix using the current API.
But suppose you have more complex case, for instance:

```javascript
var array = [0, 1, 2, 3];

// First change
array.splice(0, 0, 4, 5, 6);

// Later in your code
array.splice(1, 0, 7, 8);

// Later again
array.unshift(9);
```

I can't see any algorithm to process each records and add this information in an efficient way (I mean, nothing better than O(n^2), where n is the number of records).

In [polymer](https://github.com/Polymer/observe-js/blob/v0.0.20131107/src/observe.js#L1337), they try to merge records. It's a great idea and this should fix everything, but as you can see, it is not easy at all to implement.

> The goal has always been to be able to get a consistent view at each microtask

And you can always get it, my suggestion is just to add an information to be able to process records as it happened in your application.

> We don't provide the new value in "update" either so at least it is consistent.

You're right, but maybe this should be considered too ?

I understand this is not a trivial question because some implementations already exist, but I really think it should be considered.
