### ISSUE TITLE
Bring back Object.observe!

### ISSUE THREAD

**Issue by trusktr** [arv/ecmascript-object-observe#28]
There's nothing like Object.observe that isn't hacky.

For example, the only way to implement this with vanilla JS is to loop through an objects properties, and convert them to getters/setters and put logic in there, or if they are already getters/setters to monkey patch the logic in.

Aurelia [does this](https://github.com/aurelia/binding/blob/master/src/property-observation.js#L91-L106).

It just doesn't seem very clean, and might have unknown possible bugs due to the hack.

An official solution would have been nice. Object.observe is like MutationObserver for the DOM, which is useful.

Based on what I read [on esdiscuss](https://esdiscuss.org/topic/an-update-on-object-observe), the proposal was removed because it didn't fit the needs of Polymer, Angular, or React.

But that doesn't seem like a strong reason. Aren't there other use cases where O.o could be useful?

Are there other reasons why O.o was dropped?

**Comment by trusktr** [comment]
What was the real problem with Object.observe? It's not quite clear.

I see arguments for "immutable" and "functional", and that Proxy solves all the problems.

But functional and immutable isn't always everyone's cup of tea (high memory churn is not good for graphics performance), and Proxy is only useful to internal objects.

So far, my [`observe`](https://github.com/trusktr/james-bond/blob/master/src/observe.js) implementation works, but I know it is going to break at some point when trying to observe an object using getter/setter hacks. F.e. imagine at some point down the line someone modifies a getter/setter while not expecting an existing observer accessor to be there, and breaks it.

I find situations where simply observing an object is useful.

How am I supposed to, for example, get a DOM element and observe property changes on it with a Proxy? Having Object.observe would be straight forward and simple.

So for now, I use my `observe` tool for cases where I have a foreign object, and simply want to observe it.

The thing is, when we have full control of the creation of objects that we have references to, then it is easy to wrap them with Proxy. But there's many cases where we'd like to observe objects given to us from outside of our control.

Please, can we bring Object.observe back (and simplify it too)?

**Comment by arv** [comment]
It was also an implementation nightmare. V8 had to branch in a lot of places based on if the object was observed.

You can do a `git log -S` search in V8 git repo to see how ugly it was.
